name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  close_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
    
  print_hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: echo "Hello World!"