name: Print Hello on Push
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Details
      run: |
        pwd
        ls
        echo $GITHUB_SHA
        echo $GITHUB_REPOSITORY
        echo $GITHUB_WORKSPACE
        echo "${{ github.token }}"

